version: 0.0
os: linux

files:
  - source: ./frontend/*
    destination: /var/www/html/app
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: frontend/scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: frontend/scripts/after_install.sh
      timeout: 300
      runas: root
        
